---
notifications:
- ethenry@ucsc.edu
name: MS20_Black_Panthers_remodel
status: New
type: ingest
file_prefix: ms0020_done/
work_type: Work
file_method: remove-and-add
update_identifier: masterFilename
visibility: restricted
ignored_columns: []
ms20_black_panthers_remodel: ms20_black_panthers_remodel
ingest: ingest
OK: OK
