---
notifications:
- ethenry@ucsc.edu
name: MS20_test_4
status: New
type: ingest
file_prefix: ms0020_done/
work_type: Work
file_method: remove-and-add
update_identifier: masterFilename
visibility: open
ignored_columns: []
ms20_test_4: ms20_test_4
ingest: ingest
OK: OK
