---
notifications:
- ethenry@ucsc.edu
name: ms020_remodel_test_3
status: New
type: ingest
file_prefix: ms0020_done/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
ms020_remodel_test_3: ms020_remodel_test_3
ingest: ingest
OK: OK
