---
notifications:
- ethenry@ucsc.edu
name: UA50
status: New
type: ingest
file_prefix: ua0050/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
ua50: ua50
ingest: ingest
OK: OK
