---
notifications:
- ethenry@ucsc.edu
name: MS20_test_2
status: New
type: ingest
file_prefix: ms0020_done/
work_type: Work
file_method: remove-and-add
visibility: open
ignored_columns: []
ms20_test_2: ms20_test_2
ingest: ingest
OK: OK
